### ISSUE TITLE
Interactions need to support a fourth type

### ISSUE THREAD

**Issue by stonier** [asmodehn/rostful#26]
Currently the interaction manager supports the following interactions:

1. Launch user side application / - 
2. - / Launch robot side application
3. Launch user side application / Launch robot side application

We need one more specifically for gocart style scenarios:

* Launch user side application w/ Running robot side application as a requirement

**Comment by asmodehn** [comment]
The required field has been added to itneractions and we are checking it from rostful.
We still need to get the rapp public interface and expose the remapped topics/services

**Comment by asmodehn** [comment]
Done
