### ISSUE TITLE
Setup Dependencies as catkin packages.

### ISSUE THREAD

**Issue by asmodehn** [asmodehn/rostful#30]
Flask-Security
Flask-Migrate

**Comment by asmodehn** [comment]
Flask-CORS

**Comment by asmodehn** [comment]
Flask-Restful

**Comment by asmodehn** [comment]
flask ? gunicorn ?

**Comment by stonier** [comment]
Since we have to do this sooner or later, shall we get this one out of the way this week?

**Comment by asmodehn** [comment]
Agreed.

**Comment by asmodehn** [comment]
Put all of these dependencies ( and more ) into https://github.com/asmodehn/flask-ext-catkin
If other software require some python dependencies that are not in rosdep already, they will probably end up in the same place.

Closing this. Later we could trim down these dependencies once the scope of rostful is more defined.
