### ISSUE TITLE
indigo.rosinstall trying to checkout to non existing indigo branch of Rostful.

### ISSUE THREAD

**Issue by dhirajdhule** [asmodehn/rostful#49]
https://github.com/asmodehn/rostful/tree/indigo-devel/rostful_examples 
instructions on this page took me to install using indigo.rosinstall, which tries to checkout to indigo branch but there is only indigo-devel branch for rostful.

Its not causing any issue except error while wstool init.

**Comment by asmodehn** [comment]
Thank you for reporting this.
The indigo branch was probably lost at some point while refactoring to interface with ros via another process. I honestly cannot remember.
Anyway things have stabilized a bit now so I (re)created an indigo branch, which I believe should solve this problem.
Please let me know if you encounter any other issue while running rostful.
I ll keep this issue open for a little while, just in case.

**Comment by dhirajdhule** [comment]
Thanks.
There's one more issue.
The turtlesim_dev.launch in
roslaunch rostful turtlesim_dev.launch --screen
is not in rostful but in rostful-examples, in indigo-dev branch.
If you have corrected it in new indigo branch then there is no issue.
Anyway rostful was working fine when I used indigo-dev.rosinstall.

**Comment by asmodehn** [comment]
Fixed readme : 
https://github.com/asmodehn/rostful/commit/89c33e1b3e97e2c43175cd8b28ad7f85e71f910b
