### ISSUE TITLE
Replacing zeroconf in rocon

### ISSUE THREAD

**Issue by stonier** [asmodehn/rostful#5]
Multicast/broadcast.

Probably simple broadcast is enough. All we do is advertise an ip.

There is some example code for simple multicast style in [multimaster_fkie](http://wiki.ros.org/multimaster_fkie).

**Comment by asmodehn** [comment]
An interesting take on a similar (the exact same?) problem :
etcd(distributed consensus via graft) + skyDNS (distributed DNS with service registration) + skydock ( if we want docker ).

**Comment by asmodehn** [comment]
Actually an interesting comparison of other solutions : http://jasonwilder.com/blog/2014/02/04/service-discovery-in-the-cloud/.

And even a demo : http://www.tikalk.com/devops/docker-service-discovery-skydns-and-skydock/

**Comment by asmodehn** [comment]
moved.
