### ISSUE TITLE
wtforms.fields module dependency is missing

### ISSUE THREAD

**Issue by hughie** [asmodehn/rostful#68]
Process is died with these message.
```
/usr/bin/python: No module named wtforms.fields; 'rostful' is a package and cannot be directly executed
```

**Comment by asmodehn** [comment]
This should now be fixed in both stable(indigo) and devel (indigo-devel) branches.
Please update, check and close if it fixes the problem for you.

**Comment by asmodehn** [comment]
seems to be fixed. reopen if problem still occurs.
